const randomLetterInfo = [
  { giver: 'Steve', receiver: 'Carly', notes: 'make it poetic' },
  { giver: 'Avocado', receiver: 'Toast', notes: 'u snore a lot, toast.' },
  {
    giver: 'policeman',
    receiver: 'robber',
    notes: 'i adore u but seriously stop pilfering my goods!',
  },
  { giver: 'dog', receiver: 'cat', notes: 'woof woof, i have a crush on u' },
  { giver: 'princess', receiver: 'frog', notes: 'u r my prince charming' },
  {
    giver: 'penguin',
    receiver: 'polar bear',
    notes: 'brrrr, i have the hots for u',
  },
  { giver: 'nerd', receiver: 'geek', notes: 'i have a soft spot for u' },
  { giver: 'giraffe', receiver: 'lion', notes: 'stretch my neck for u' },
  { giver: 'pirate', receiver: 'mermaid', notes: "ahoy matey, i'm sweet on u" },
  { giver: 'cow', receiver: 'bull', notes: 'moo, u r my bovine love' },
  { giver: 'hippo', receiver: 'gazelle', notes: "i'm heavy with love for u" },
  {
    giver: 'butterfly',
    receiver: 'caterpillar',
    notes: 'flutter my wings for u',
  },
  {
    giver: 'robot',
    receiver: 'robot',
    notes: 'beep boop, i have a circuit for u',
  },
  { giver: 'dolphin', receiver: 'whale', notes: 'splash my tail for u' },
  {
    giver: 'santa',
    receiver: 'elf',
    notes: 'ho ho ho, i have a present for u',
  },
  { giver: 'granny', receiver: 'grandpa', notes: "i'm sweet on u like my tea" },
  { giver: 'sun', receiver: 'moon', notes: 'i shine brighter with u' },
  {
    giver: 'astronaut',
    receiver: 'aliens',
    notes: 'take me to your leader... of love',
  },
  { giver: 'Bubbles', receiver: 'Buttercup', notes: 'U have da power of love' },
  { giver: 'Llama', receiver: 'Alpaca', notes: 'Llama always love you more' },
  {
    giver: 'Homer',
    receiver: 'Marge',
    notes: "Donut know what I'd do without you",
  },
  { giver: 'Batman', receiver: 'Robin', notes: "You're my sidekick in love" },
  {
    giver: 'Mickey',
    receiver: 'Minnie',
    notes: 'U complete me like cheese n crackers',
  },
  {
    giver: 'Spongebob',
    receiver: 'Patrick',
    notes: 'U r my best friend n love',
  },
  { giver: 'Harry', receiver: 'Hermione', notes: 'Wizards in love forever' },
  { giver: 'Dory', receiver: 'Nemo', notes: "Just keep lovin' each other" },
  { giver: 'Buzz', receiver: 'Woody', notes: 'To infinity n beyond in love' },
  { giver: 'Kermit', receiver: 'Miss Piggy', notes: "Somebody's got a crush" },
  { giver: 'Donald', receiver: 'Daisy', notes: 'Quack quack, love forever' },
  {
    giver: 'Goofy',
    receiver: 'Pluto',
    notes: 'Just love being silly together',
  },
  { giver: 'Simba', receiver: 'Nala', notes: 'Lion king of love' },
  { giver: 'Ralph', receiver: 'Vanellope', notes: 'Wreck-it love' },
  { giver: 'Pikachu', receiver: 'Charmander', notes: 'Electric love sparks' },
  { giver: 'Olaf', receiver: 'Anna', notes: 'Snowman in love all summer' },
];

export default randomLetterInfo;
